name = "ADTensor"
uuid = "1846a12a-bf3c-41d7-8528-153c1dad55cd"
authors = ["Xingyu Zhang <zhangxingyu@iphy.ac.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
